# Preprocessing

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

In [15]:
df = pd.read_csv('raw/AOIBaseTFG.tsv', sep='\t')


claro = df[df['Timeline'] == 'Timeline1-Mode1']
oscuro = df[df['Timeline'] == 'Timeline2-Mode2']

## Erase invalid data

In [16]:
claro.describe()

,Interval,Total_duration_of_fixations,Number_of_fixations,Time_to_first_fixation,Number_of_saccades_in_AOI,Time_to_entry_saccade,Time_to_exit_saccade
count,21080.0,21080.000000,21080.000000,7886.000000,21080.000000,7360.000000,7280.000000
mean,1.0,254.510531,0.801423,105880.262744,0.269165,105655.056114,105978.192033
std,0.0,1287.603949,3.821748,86151.793323,3.088329,85783.424784,86023.278155
min,1.0,0.000000,0.000000,0.000000,0.000000,13.000000,17.000000
25%,1.0,0.000000,0.000000,28758.500000,0.000000,28842.750000,29026.750000
50%,1.0,0.000000,0.000000,89748.000000,0.000000,89979.000000,89891.000000
75%,1.0,233.000000,1.000000,167660.250000,0.000000,167148.750000,167859.500000
max,1.0,34142.000000,76.000000,382741.000000,69.000000,382691.000000,383507.000000

In [17]:
oscuro.describe()

,Interval,Total_duration_of_fixations,Number_of_fixations,Time_to_first_fixation,Number_of_saccades_in_AOI,Time_to_entry_saccade,Time_to_exit_saccade
count,21080.0,21080.000000,21080.000000,7990.000000,21080.000000,6978.000000,6909.000000
mean,1.0,227.594213,0.836622,110130.386984,0.255313,106805.400545,106871.268346
std,0.0,1123.564022,4.067772,90300.560150,2.858657,86902.945700,87118.377432
min,1.0,0.000000,0.000000,0.000000,0.000000,13.000000,2.000000
25%,1.0,0.000000,0.000000,28167.250000,0.000000,27283.500000,27126.000000
50%,1.0,0.000000,0.000000,97499.000000,0.000000,92571.000000,92067.000000
75%,1.0,217.000000,1.000000,180286.000000,0.000000,176123.250000,176357.000000
max,1.0,29379.000000,124.000000,424896.000000,72.000000,424846.000000,425162.000000

# Time to first Fixation

## General (total of AOIs)

In [18]:
def obtainBasicData(array):
    mean = np.mean(array)
    
    std = np.std(array)
    max = np.max(array)
    min = np.min(array)
    return mean, std, max, min

In [19]:

ttf_ColImgs_claro = claro[claro['AOI'] == 'ColumnaIzquierdaImagenes']['Time_to_first_fixation']
ttf_ColImgs_oscuro = oscuro[oscuro['AOI'] == 'ColumnaIzquierdaImagenes']['Time_to_first_fixation']

mean_claro, std_claro, max_claro, min_claro = obtainBasicData(ttf_ColImgs_claro)
mean_oscuro, std_oscuro, max_oscuro, min_oscuro = obtainBasicData(ttf_ColImgs_oscuro)
print("Columna Izquierda Imagenes - Tiempo hasta la primera fijación")
print(f"Claro - Mean: {mean_claro:.2f},  Std: {std_claro:.2f}, Max: {max_claro:.2f}, Min: {min_claro:.2f}")
print(f"Oscuro - Mean: {mean_oscuro:.2f},  Std: {std_oscuro:.2f}, Max: {max_oscuro:.2f}, Min: {min_oscuro:.2f}")

Columna Izquierda Imagenes - Tiempo hasta la primera fijación
Claro - Mean: 96459.10,  Std: 84161.71, Max: 212783.00, Min: 584.00
Oscuro - Mean: 142321.83,  Std: 96516.48, Max: 293203.00, Min: 930.00